name: Example Release

on:
  push:
    tags:
      - 'release/v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/release/}" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64
          file: .github/actions/Dockerfile
          push: true
          secrets: |
            username=robhillier
            token=${{ secrets.PAT }}
          tags: |
            hi/ithb/a

